variable "costfluent_account_id" {
  description = "Costfluent's AWS account ID, shown on the connection page. Trusted to assume the role."
  type        = string

  validation {
    condition     = can(regex("^[0-9]{12}$", var.costfluent_account_id))
    error_message = "Must be a 12-digit AWS account ID."
  }
}

variable "external_id" {
  description = "External ID for the assume-role handshake. Generated by Costfluent; do not invent one."
  type        = string

  validation {
    condition     = length(var.external_id) >= 8
    error_message = "External ID must be at least 8 characters."
  }
}

variable "role_name" {
  description = "Name of the IAM role Costfluent assumes."
  type        = string
  default     = "CostfluentBillingRole"

  validation {
    condition     = can(regex("^[a-zA-Z0-9+=,.@_-]{1,64}$", var.role_name))
    error_message = "Must be a valid IAM role name (up to 64 characters)."
  }
}

variable "max_session_duration" {
  description = "Maximum lifetime, in seconds, of a session Costfluent assumes."
  type        = number
  default     = 3600

  validation {
    condition     = var.max_session_duration >= 3600 && var.max_session_duration <= 43200
    error_message = "AWS allows between 3600 and 43200 seconds."
  }
}

variable "tags" {
  description = "Tags applied to the IAM role."
  type        = map(string)
  default     = {}
}
