variable "region" {
  description = "Region the provider authenticates in. IAM is global; this only picks an endpoint."
  type        = string
  default     = "us-east-1"
}

variable "costfluent_account_id" {
  description = "Costfluent's AWS account ID, from the connection page."
  type        = string
}

variable "external_id" {
  description = "External ID generated by Costfluent for this connection."
  type        = string
}
